apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "remnawave-subscription-page.fullname" . }}
  labels:
    {{- include "remnawave-subscription-page.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "remnawave-subscription-page.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "remnawave-subscription-page.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "remnawave-subscription-page.fullname" . }}
            - secretRef:
                name: {{ if .Values.app.existingSecret }}{{ .Values.app.existingSecret }}{{ else }}{{ include "remnawave-subscription-page.fullname" . }}{{ end }}
          env:
            - name: REMNAWAVE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.app.existingSecret }}{{ .Values.app.existingSecret }}{{ else }}{{ include "remnawave-subscription-page.fullname" . }}{{ end }}
                  key: {{ .Values.app.apiTokenKey | default "apiToken" }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
                - name: X-Forwarded-For
                  value: 127.0.0.1
          readinessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
                - name: X-Forwarded-For
                  value: 127.0.0.1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
