{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnawave-subscription-page.fullname" . }}
  labels:
    {{- include "remnawave-subscription-page.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiToken: {{ .Values.app.apiToken | quote }}
  {{- if .Values.app.marzbanLegacySecretKey }}
  MARZBAN_LEGACY_SECRET_KEY: {{ .Values.app.marzbanLegacySecretKey | quote }}
  {{- end }}
  {{- if .Values.app.caddyAuthApiToken }}
  CADDY_AUTH_API_TOKEN: {{ .Values.app.caddyAuthApiToken | quote }}
  {{- end }}
  {{- if .Values.app.cloudflareZeroTrustClientId }}
  CLOUDFLARE_ZERO_TRUST_CLIENT_ID: {{ .Values.app.cloudflareZeroTrustClientId | quote }}
  {{- end }}
  {{- if .Values.app.cloudflareZeroTrustClientSecret }}
  CLOUDFLARE_ZERO_TRUST_CLIENT_SECRET: {{ .Values.app.cloudflareZeroTrustClientSecret | quote }}
  {{- end }}
{{- end }}
