{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnawave-subscription-page.fullname" . }}
  labels:
    {{- include "remnawave-subscription-page.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiToken: {{ .Values.app.apiToken | quote }}
{{- end }}
